name: Deploy to InfinityFree via FTP

on:
  push:
    branches:
      - main # trigger on pushes to main branch

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure db.php
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["${{ github.workspace}}/www/php/config/db.php"]'
        env:
          MYSQL_HOSTNAME: ${{ secrets.MYSQL_HOSTNAME }}
          MYSQL_DBNAME: ${{ secrets.MYSQL_DBNAME }}
          MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21 # default FTP port
          local-dir: ./www/ # folder in your repo to upload
          server-dir: /htdocs/ # remote directory on the FTP server
          dangerous-clean-slate: true
